export interface IconItem {
    label: string
    items: { label: string, value: string }[]
}

export const iconItems: IconItem[] = [
    {
        label: 'General',
        items: [
            { label: 'User', value: 'lucide:user' },
            { label: 'User check', value: 'lucide:user-check' },
            { label: 'Users', value: 'lucide:users' },
            { label: 'User x', value: 'lucide:user-x' },
            { label: 'Circle user', value: 'lucide:circle-user' },
            { label: 'Circle x', value: 'lucide:circle-x' },
            { label: 'Circle power', value: 'lucide:circle-power' },
            { label: 'Circle plus', value: 'lucide:circle-plus' },
            { label: 'Circle question mark', value: 'lucide:circle-question-mark' },
            { label: 'Contact', value: 'lucide:contact' },
            { label: 'Contact round', value: 'lucide:contact-round' },
            { label: 'Command', value: 'lucide:command' },
            { label: 'Copy x', value: 'lucide:copy-x' },
            { label: 'Copy', value: 'lucide:copy' },
            { label: 'Copy check', value: 'lucide:copy-check' },
            { label: 'Copy minus', value: 'lucide:copy-minus' },
            { label: 'Copy slash', value: 'lucide:copy-slash' },
            { label: 'Dice 6', value: 'lucide:dice-6' },
            { label: 'Dice 5', value: 'lucide:dice-5' },
            { label: 'Dice 4', value: 'lucide:dice-4' },
            { label: 'Dice 3', value: 'lucide:dice-3' },
            { label: 'Dice 2', value: 'lucide:dice-2' },
            { label: 'Dice 1', value: 'lucide:dice-1' },
            { label: 'Expand', value: 'lucide:expand' },
            { label: 'External link', value: 'lucide:external-link' },
            { label: 'Eye', value: 'lucide:eye' },
            { label: 'Eye off', value: 'lucide:eye-off' },
            { label: 'Fingerprint pattern', value: 'lucide:fingerprint-pattern' },
            { label: 'Hat glasses', value: 'lucide:hat-glasses' },
            { label: 'Layers', value: 'lucide:layers' },
            { label: 'Layers 2', value: 'lucide:layers-2' },
            { label: 'Layout dashboard', value: 'lucide:layout-dashboard' },
            { label: 'Layout grid', value: 'lucide:layout-grid' },
            { label: 'Layout list', value: 'lucide:layout-list' },
            { label: 'Mail', value: 'lucide:mail' },
            { label: 'Mails', value: 'lucide:mails' },
            { label: 'Map pin', value: 'lucide:map-pin' },
            { label: 'Map', value: 'llucide:map' },
            { label: 'Message circle', value: 'lucide:message-circle' },
            { label: 'Message square', value: 'lucide:message-square' },
            { label: 'Music', value: 'lucide:music' },
            { label: 'Music 2', value: 'lucide:music-2' },
            { label: 'Settings', value: 'lucide:settings' },
            { label: 'Settings 2', value: 'lucide:settings-2' },
            { label: 'Cog', value: 'lucide:cog' },
            { label: 'Share', value: 'lucide:share' },
            { label: 'Save', value: 'lucide:save' },
            { label: 'Save all', value: 'lucide:save-all' },
            { label: 'Sliders horizontal', value: 'lucide:sliders-horizontal' },
            { label: 'Sliders vertical', value: 'lucide:sliders-vertical' },
            { label: 'Venus', value: 'lucide:venus' },
            { label: 'Venus and mars', value: 'lucide:venus-and-mars' },
            { label: 'Mars', value: 'lucide:mars' },
        ]
    },
    {
        label: 'Gráficos',
        items: [
            { label: 'Chart big', value: 'lucide:chart-column-big' },
            { label: 'Chart axes combined', value: 'lucide:chart-no-axes-combined' },
            { label: 'Chart line', value: 'lucide:chart-line' },
            { label: 'Chart pie', value: 'lucide:chart-pie' },
            { label: 'Chart network', value: 'lucide:chart-network' },
            { label: 'Chart scatter', value: 'lucide:chart-scatter' },
            { label: 'Chart spline', value: 'lucide:chart-spline' },
            { label: 'Chart area', value: 'lucide:chart-area' },
            { label: 'Chart axes column', value: 'lucide:chart-no-axes-column' },
            { label: 'Chart column stacked', value: 'lucide:chart-column-stacked' },
            { label: 'Chart column', value: 'lucide:chart-column' },
            { label: 'Chart bar increasing', value: 'lucide:chart-bar-increasing' },
            { label: 'Chart candlestick', value: 'lucide:chart-candlestick' },
        ]
    },
    {
        label: 'Educação',
        items: [
            { label: 'Backpack', value: 'lucide:backpack' },
            { label: 'School', value: 'lucide:school' },
            { label: 'Bell', value: 'lucide:bell' },
            { label: 'Book open', value: 'lucide:book-open-text' },
            { label: 'Bookmark', value: 'lucide:bookmark' },
            { label: 'Bookmark plus', value: 'lucide:bookmark-plus' },
            { label: 'Bookmark check', value: 'lucide:bookmark-check' },
            { label: 'Graduation cap', value: 'lucide:graduation-cap' },
        ]
    },
    {
        label: 'Ficheiro',
        items: [
            { label: 'File Spreadsheet', value: 'lucide:file-spreadsheet' },
            { label: 'File Stack', value: 'lucide:file-stack' },
            { label: 'Files', value: 'lucide:files' },
            { label: 'File Text', value: 'lucide:file-text' },
            { label: 'File Pen', value: 'lucide:file-pen' },
            { label: 'File Chart Column Increasing', value: 'lucide:file-chart-column-increasing' },
            { label: 'File Cog', value: 'lucide:file-cog' },
            { label: 'File Badge', value: 'lucide:file-badge' },
            { label: 'File Box', value: 'lucide:file-box' },
            { label: 'File Braces', value: 'lucide:file-braces' },
            { label: 'File Chart Column', value: 'lucide:file-chart-column' },
            { label: 'File Chart Pie', value: 'lucide:file-chart-pie' },
            { label: 'File Clock', value: 'lucide:file-clock' },
            { label: 'File Type', value: 'lucide:file-type' },
            { label: 'File Video Camera', value: 'lucide:file-video-camera' },
            { label: 'File Symlink', value: 'lucide:file-symlink' },
            { label: 'File Diff', value: 'lucide:file-diff' },
            { label: 'File Question Mark', value: 'lucide:file-question-mark' },
            { label: 'File Exclamation Point', value: 'lucide:file-exclamation-point' },
            { label: 'File Scan', value: 'lucide:file-scan' },
            { label: 'Folder', value: 'lucide:folder' },
            { label: 'Folder Plus', value: 'lucide:folder-plus' },
            { label: 'Folder X', value: 'lucide:folder-x' },
            { label: 'Folder Tree', value: 'lucide:folder-tree' },
            { label: 'Folder Code', value: 'lucide:folder-code' },
            { label: 'Folder Git 2', value: 'lucide:folder-git-2' },
            { label: 'Folder Cog', value: 'lucide:folder-cog' },
            { label: 'Folder Check', value: 'lucide:folder-check' },
            { label: 'Folders', value: 'lucide:folders' },
            { label: 'Folder Search 2', value: 'lucide:folder-search-2' },
            { label: 'Folder Open', value: 'lucide:folder-open' },
            { label: 'Folder Key', value: 'lucide:folder-key' },
            { label: 'Folder Lock', value: 'lucide:folder-lock' },
            { label: 'Folder Heart', value: 'lucide:folder-heart' },
        ]
    },
    {
        label: 'Ferramentas',
        items: [
            { label: 'Briefcase', value: 'lucide:briefcase' },
            { label: 'School', value: 'lucide:briefcase-business' },
            { label: 'Bell', value: 'lucide:briefcase-conveyor-belt' },
            { label: 'Book open', value: 'lucide:briefcase-medical' },
            { label: 'Bookmark', value: 'lucide:camera' },
            { label: 'Bookmark plus', value: 'lucide:bookmark-plus' },
            { label: 'Bookmark check', value: 'lucide:bookmark-check' },
            { label: 'Utensils', value: 'lucide:utensils' },
            { label: 'Scale', value: 'lucide:scale' },
            { label: 'Scale', value: 'lucide:scale' },
            { label: 'Martini', value: 'lucide:martini' },
            { label: 'Key round', value: 'lucide:key-round' },
            { label: 'Lightbulb', value: 'lucide:lightbulb' },
            { label: 'Lamp', value: 'lucide:lamp' },
            { label: 'Lamp desk', value: 'lucide:lamp-desk' },
            { label: 'Hammer', value: 'lucide:hammer' },
            { label: 'Brush cleaning', value: 'lucide:brush-cleaning' },
            { label: 'Award', value: 'lucide:award' },
            { label: 'Hard hat', value: 'lucide:hard-hat' },
        ]
    },
    {
        label: 'Tecnologia',
        items: [
            { label: 'Battery full', value: 'lucide:battery-full' },
            { label: 'Database', value: 'lucide:database' },
            { label: 'Database backup', value: 'lucide:database-backup' },
            { label: 'Database search', value: 'lucide:database-search' },
            { label: 'Laptop', value: 'lucide:laptop' },
            { label: 'Laptop minimal', value: 'lucide:laptop-minimal' },
            { label: 'Laptop minimal check', value: 'lucide:laptop-minimal-check' },
            { label: 'Monitor', value: 'lucide:monitor' },
            { label: 'Monitor check', value: 'lucide:monitor-check' },
            { label: 'Monitor play', value: 'lucide:monitor-play' },
            { label: 'Monitor smartphone', value: 'lucide:monitor-smartphone' },
            { label: 'Mouse', value: 'lucide:mouse' },
            { label: 'Smartphone', value: 'lucide:smartphone' },
            { label: 'Smartphone charging', value: 'lucide:smartphone-charging' },
            { label: 'Tablet smartphone', value: 'lucide:tablet-smartphone' },
            { label: 'Video', value: 'lucide:video' },
            { label: 'Keyboard', value: 'lucide:keyboard' },
            { label: 'Gamepad', value: 'lucide:gamepad-2' },
            { label: 'Network', value: 'lucide:network' },
            { label: 'Phone', value: 'lucide:phone' },
            { label: 'Phone call', value: 'lucide:phone-call' },
            { label: 'Server', value: 'lucide:server' },
            { label: 'Server cog', value: 'lucide:server-cog' },
            { label: 'Printer', value: 'lucide:printer' },
            { label: 'Printer check', value: 'lucide:printer-check' },
            { label: 'Printer off', value: 'lucide:printer-off' },
            { label: 'Projector', value: 'lucide:projector' },
            { label: 'QR code', value: 'lucide:qr-code' },
            { label: 'Radio tower', value: 'lucide:radio-tower' },
            { label: 'Route', value: 'lucide:route' },
            { label: 'Router', value: 'lucide:router' },
            { label: 'Code xml', value: 'lucide:code-xml' },
            { label: 'Code', value: 'lucide:code' },
        ]
    },
    {
        label: 'Transporte',
        items: [
            { label: 'Car', value: 'lucide:car' },
            { label: 'Bus', value: 'lucide:bus' },
            { label: 'Train', value: 'lucide:train' },
            { label: 'Truck', value: 'lucide:truck' },
            { label: 'Bicycle', value: 'lucide:bicycle' },
            { label: 'Car front', value: 'lucide:car-front' },
            { label: 'Car taxi front', value: 'lucide:car-taxi-front' },
            { label: 'Caravan', value: 'lucide:caravan' },
            { label: 'Plane', value: 'lucide:plane' },
            { label: 'Ship', value: 'lucide:ship' },
            { label: 'Train', value: 'lucide:train' },
            { label: 'Plane takeoff', value: 'lucide:plane-takeoff' },
            { label: 'Plane landing', value: 'lucide:plane-landing' },
            { label: 'Cable car', value: 'lucide:cable-car' },
        ]
    },
    {
        label: 'Tempo',
        items: [
            { label: 'Clock', value: 'lucide:clock' },
            { label: 'Clock 1', value: 'lucide:clock-1' },
            { label: 'Cloud', value: 'lucide:cloud' },
            { label: 'Cloud cog', value: 'lucide:cloud-cog' },
            { label: 'Cloud drizzle', value: 'lucide:cloud-drizzle' },
            { label: 'Cloud lightning', value: 'lucide:cloud-lightning' },
            { label: 'Cloudy', value: 'lucide:cloudy' },
            { label: 'Cloud backup', value: 'lucide:cloud-backup' },
            { label: 'Cloud rain wind', value: 'lucide:cloud-rain-wind' },
            { label: 'Cloud rain wind', value: 'lucide:cloud-rain-wind' },
            { label: 'Cloud off', value: 'lucide:cloud-off' },
            { label: 'Club', value: 'lucide:club' },
            { label: 'Cloud sun', value: 'lucide:cloud-sun' },
            { label: 'Cloud sun rain', value: 'lucide:cloud-sun-rain' },
            { label: 'Sun', value: 'lucide:sun' },
            { label: 'Sun moon', value: 'lucide:sun-moon' },
            { label: 'Sun snow', value: 'lucide:sun-snow' },
            { label: 'Sunrise', value: 'lucide:sunrise' },
            { label: 'Sunset', value: 'lucide:sunset' },
            { label: 'Moon', value: 'lucide:moon' },
            { label: 'Cannabis', value: 'lucide:cannabis' },
            { label: 'Cannabis off', value: 'lucide:cannabis-off' },
            { label: 'Candy cane', value: 'lucide:candy-cane' },
            { label: 'Calendar', value: 'lucide:calendar' },
            { label: 'Calendar days', value: 'lucide:calendar-days' },
            { label: 'Calendar cog', value: 'lucide:calendar-cog' },
            { label: 'Calendar plus 2', value: 'lucide:calendar-plus-2' },
            { label: 'Calendar x', value: 'lucide:calendar-x' },
            { label: 'Calendar range', value: 'lucide:calendar-range' },
            { label: 'Calendar check', value: 'lucide:calendar-check' },
            { label: 'Calendar minus 2', value: 'lucide:calendar-minus-2' },
            { label: 'Calendar off', value: 'lucide:calendar-off' },
            { label: 'Calendar heart', value: 'lucide:calendar-heart' },
            { label: 'Calendar clock', value: 'lucide:calendar-clock' },
        ]
    },
    {
        label: 'Setas',
        items: [
            { label: 'Arrow big down', value: 'lucide:arrow-big-down' },
            { label: 'Arrow big up', value: 'lucide:arrow-big-up' },
            { label: 'Arrow big left', value: 'lucide:arrow-big-left' },
            { label: 'Arrow big right', value: 'lucide:arrow-big-right' },
            { label: 'Arrow down', value: 'lucide:arrow-down' },
            { label: 'Arrow up', value: 'lucide:arrow-up' },
            { label: 'Arrow left', value: 'lucide:arrow-left' },
            { label: 'Arrow right', value: 'lucide:arrow-right' },
            { label: 'Arrow up right', value: 'lucide:arrow-up-right' },
            { label: 'Arrow down right', value: 'lucide:arrow-down-right' },
            { label: 'Arrow up left', value: 'lucide:arrow-up-left' },
            { label: 'Arrow down left', value: 'lucide:arrow-down-left' },
            { label: 'Square arrow down', value: 'lucide:square-arrow-down' },
            { label: 'Square arrow up', value: 'lucide:square-arrow-up' },
            { label: 'Square arrow left', value: 'lucide:square-arrow-left' },
            { label: 'Square arrow right', value: 'lucide:square-arrow-right' },
            { label: 'Square arrow out down left', value: 'lucide:square-arrow-out-down-left' },
            { label: 'Square arrow out down right', value: 'lucide:square-arrow-out-down-right' },
            { label: 'Square arrow out up left', value: 'lucide:square-arrow-out-up-left' },
            { label: 'Square arrow out up right', value: 'lucide:square-arrow-out-up-right' },
            { label: 'Circle arrow down', value: 'lucide:circle-arrow-down' },
            { label: 'Circle arrow up', value: 'lucide:circle-arrow-up' },
            { label: 'Circle arrow left', value: 'lucide:circle-arrow-left' },
            { label: 'Circle arrow right', value: 'lucide:circle-arrow-right' },
            { label: 'Circle arrow out down left', value: 'lucide:circle-arrow-out-down-left' },
            { label: 'Circle arrow out down right', value: 'lucide:circle-arrow-out-down-right' },
            { label: 'Circle arrow out up left', value: 'lucide:circle-arrow-out-up-left' },
            { label: 'Circle arrow out up right', value: 'lucide:circle-arrow-out-up-right' },
            { label: 'Corner down left', value: 'lucide:corner-down-left' },
            { label: 'Corner down right', value: 'lucide:corner-down-right' },
            { label: 'Corner up left', value: 'lucide:corner-up-left' },
            { label: 'Corner up right', value: 'lucide:corner-up-right' },
            { label: 'Move down', value: 'lucide:move-down' },
            { label: 'Move up', value: 'lucide:move-up' },
            { label: 'Move left', value: 'lucide:move-left' },
            { label: 'Move right', value: 'lucide:move-right' },
            { label: 'Move down left', value: 'lucide:move-down-left' },
            { label: 'Move down right', value: 'lucide:move-down-right' },
            { label: 'Move up left', value: 'lucide:move-up-left' },
            { label: 'Move up right', value: 'lucide:move-up-right' },
            { label: 'Repeat', value: 'lucide:repeat' },
            { label: 'Repeat 2', value: 'lucide:repeat-2' },
            { label: 'Refresh ccw', value: 'lucide:refresh-ccw' },
            { label: 'Rotate cw', value: 'lucide:rotate-cw' },
            { label: 'Chevron left', value: 'lucide:chevron-left' },
            { label: 'Chevron right', value: 'lucide:chevron-right' },
            { label: 'Chevron up', value: 'lucide:chevron-up' },
            { label: 'Chevron down', value: 'lucide:chevron-down' },
            { label: 'Chevrons left', value: 'lucide:chevrons-left' },
            { label: 'Chevrons right', value: 'lucide:chevrons-right' },
            { label: 'Chevrons up', value: 'lucide:chevrons-up' },
            { label: 'Chevrons down', value: 'lucide:chevrons-down' },
        ]
    },
];